package Bachelor.Gateway;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

import org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;

@SpringBootApplication(exclude = {SecurityAutoConfiguration.class })
public class GatewayApplication {

	public static void main(String[] args) throws InterruptedException {
		SpringApplication.run(GatewayApplication.class, args);

		Neo4jDriver neo4jDriver = new Neo4jDriver("neo4j://localhost:7687", "neo4j", "demo");
		ArrayList<String> webParts = new ArrayList<String>();
		webParts.add("Admin");
		//webParts.add("Messages");
		String sdkuiPart = "src/components/analytics/tabs/MessagesTab.tsx\n" +
				"src/components/analytics/tabs/MobileDevicesTab.tsx\n";
		String sdkui = "src/Helper.test.ts\n" +
				"src/Helper.ts\n" +
				"src/components/accordion/Accordion.css\n" +
				"src/components/accordion/Accordion.tsx\n" +
				"src/components/advancedSettings/AdvancedSettings.css\n" +
				"src/components/advancedSettings/AdvancedSettings.tsx\n" +
				"src/components/analytics/Analytics.css\n" +
				"src/components/analytics/Analytics.tsx\n" +
				"src/components/analytics/detailsList/DetailsList.css\n" +
				"src/components/analytics/detailsList/DetailsList.tsx\n" +
				"src/components/analytics/index.tsx\n" +
				"src/components/analytics/stores/AnalyticsStore.ts\n" +
				"src/components/analytics/stores/index.ts\n" +
				"src/components/analytics/tabs/MessagesTab.tsx\n" +
				"src/components/analytics/tabs/MobileDevicesTab.tsx\n" +
				"src/components/app/App.css\n" +
				"src/components/app/App.tsx\n" +
				"src/components/app/Index.tsx\n" +
				"src/components/app/admin/addComponentButton/AddComponentButton.css\n" +
				"src/components/app/admin/addComponentButton/AddComponentButton.tsx\n" +
				"src/components/app/admin/componentEditPanel/ComponentEditPanel.css\n" +
				"src/components/app/admin/componentEditPanel/ComponentEditPanel.tsx\n" +
				"src/components/app/admin/designEditPanel/DesignEditPanel.css\n" +
				"src/components/app/admin/designEditPanel/DesignEditPanel.tsx\n" +
				"src/components/app/admin/pageEditPanel/PageEditPanel.css\n" +
				"src/components/app/admin/pageEditPanel/PageEditPanel.tsx\n" +
				"src/components/app/admin/pushSettingsPanel/PushSettingsPanel.css\n" +
				"src/components/app/admin/pushSettingsPanel/PushSettingsPanel.tsx\n" +
				"src/components/app/admin/sortPagesPanel/SortPagesPanel.css\n" +
				"src/components/app/admin/sortPagesPanel/SortPagesPanel.tsx\n" +
				"src/components/app/contentArea/ContentArea.css\n" +
				"src/components/app/contentArea/ContentArea.tsx\n" +
				"src/components/app/contentArea/contentMapPanel/ContentMapPanel.css\n" +
				"src/components/app/contentArea/contentMapPanel/ContentMapPanel.tsx\n" +
				"src/components/app/contentArea/navigatorPanel/NavigatorPanel.css\n" +
				"src/components/app/contentArea/navigatorPanel/NavigatorPanel.tsx\n" +
				"src/components/app/menu/Menu.css\n" +
				"src/components/app/menu/Menu.tsx\n" +
				"src/components/app/menu/menuItem/MenuItem.css\n" +
				"src/components/app/menu/menuItem/MenuItem.tsx\n" +
				"src/components/app/navigationBar/NavigationBar.css\n" +
				"src/components/app/navigationBar/NavigationBar.tsx\n" +
				"src/components/app/settings.json\n" +
				"src/components/app/settings/Settings.css\n" +
				"src/components/app/settings/Settings.tsx\n" +
				"src/components/app/stores/AppStore.ts\n" +
				"src/components/app/stores/index.ts\n" +
				"src/components/app/tabBar/TabBar.css\n" +
				"src/components/app/tabBar/TabBar.tsx\n" +
				"src/components/app/tabBar/tabBarItem/TabBarItem.css\n" +
				"src/components/app/tabBar/tabBarItem/TabBarItem.tsx\n" +
				"src/components/app/tabBarPanel/TabBarPanel.css\n" +
				"src/components/app/tabBarPanel/TabBarPanel.tsx\n" +
				"src/components/app/tabBarPanel/tabBarPanelItem/TabBarPanelItem.css\n" +
				"src/components/app/tabBarPanel/tabBarPanelItem/TabBarPanelItem.tsx\n" +
				"src/components/appAdmin/AppAdmin.css\n" +
				"src/components/appAdmin/AppAdmin.tsx\n" +
				"src/components/appAdmin/Index.tsx\n" +
				"src/components/appAdmin/stores/AppAdminStore.ts\n" +
				"src/components/appAdmin/stores/index.ts\n" +
				"src/components/attachments/Attachments.css\n" +
				"src/components/attachments/Attachments.tsx\n" +
				"src/components/basicCard/BasicCard.css\n" +
				"src/components/basicCard/BasicCard.tsx\n" +
				"src/components/birthdays/Birthdays.tsx\n" +
				"src/components/birthdays/cardView/CardView.css\n" +
				"src/components/birthdays/cardView/CardView.tsx\n" +
				"src/components/birthdays/cardView/peopleCard/peopleCard.css\n" +
				"src/components/birthdays/cardView/peopleCard/peopleCard.tsx\n" +
				"src/components/birthdays/listView/ListView.css\n" +
				"src/components/birthdays/listView/ListView.tsx\n" +
				"src/components/birthdays/listView/personaSmall/PersonaSmall.css\n" +
				"src/components/birthdays/listView/personaSmall/PersonaSmall.tsx\n" +
				"src/components/button/Button.css\n" +
				"src/components/button/Button.test.tsx\n" +
				"src/components/button/Button.tsx\n" +
				"src/components/card/Card.css\n" +
				"src/components/card/Card.tsx\n" +
				"src/components/card/cover/CardCover.css\n" +
				"src/components/card/cover/CardCover.tsx\n" +
				"src/components/card/footer/CardFooter.css\n" +
				"src/components/card/footer/CardFooter.tsx\n" +
				"src/components/cardView/CardView.service.ts\n" +
				"src/components/cardView/CardView.test.ts\n" +
				"src/components/cardView/CardView.tsx\n" +
				"src/components/carousel/Carousel.css\n" +
				"src/components/carousel/Carousel.tsx\n" +
				"src/components/carousel/carouselContentElement/CarouselContentElement.css\n" +
				"src/components/carousel/carouselContentElement/CarouselContentElement.tsx\n" +
				"src/components/categories/Categories.css\n" +
				"src/components/categories/Categories.tsx\n" +
				"src/components/categories/panels/syncPanel/SyncPanel.css\n" +
				"src/components/categories/panels/syncPanel/SyncPanel.tsx\n" +
				"src/components/checkbox/Checkbox.css\n" +
				"src/components/checkbox/Checkbox.tsx\n" +
				"src/components/choiceGroup/ChoiceGroup.css\n" +
				"src/components/choiceGroup/ChoiceGroup.tsx\n" +
				"src/components/codeEditor/CodeEditor.css\n" +
				"src/components/codeEditor/CodeEditor.tsx\n" +
				"src/components/colorPicker/ColorPicker.css\n" +
				"src/components/colorPicker/ColorPicker.tsx\n" +
				"src/components/commandBar/CommandBar.css\n" +
				"src/components/commandBar/CommandBar.tsx\n" +
				"src/components/comments/Comments.css\n" +
				"src/components/comments/Comments.tsx\n" +
				"src/components/composer/Composer.css\n" +
				"src/components/composer/Composer.tsx\n" +
				"src/components/composer/Index.tsx\n" +
				"src/components/composer/controller/Controller.css\n" +
				"src/components/composer/controller/Controller.tsx\n" +
				"src/components/composer/cover/Cover.css\n" +
				"src/components/composer/cover/Cover.tsx\n" +
				"src/components/composer/gallery/Gallery.css\n" +
				"src/components/composer/gallery/Gallery.tsx\n" +
				"src/components/composer/gallery/collage/Collage.css\n" +
				"src/components/composer/gallery/collage/Collage.tsx\n" +
				"src/components/composer/gallery/rotator/Rotator.css\n" +
				"src/components/composer/gallery/rotator/Rotator.tsx\n" +
				"src/components/composer/gallery/tiles/Tiles.css\n" +
				"src/components/composer/gallery/tiles/Tiles.tsx\n" +
				"src/components/composer/helper/ComposerHelper.ts\n" +
				"src/components/composer/image/Image.css\n" +
				"src/components/composer/image/Image.tsx\n" +
				"src/components/composer/image/organizationalAssetPanel/OrganizationalAssetPanel.css\n" +
				"src/components/composer/image/organizationalAssetPanel/OrganizationalAssetPanel.tsx\n" +
				"src/components/composer/preview/Preview.css\n" +
				"src/components/composer/preview/Preview.tsx\n" +
				"src/components/composer/settings/Settings.css\n" +
				"src/components/composer/settings/Settings.tsx\n" +
				"src/components/composer/settings/approvalDetails/ApprovalDetails.css\n" +
				"src/components/composer/settings/approvalDetails/ApprovalDetails.tsx\n" +
				"src/components/composer/stores/Store.ts\n" +
				"src/components/composer/stores/index.ts\n" +
				"src/components/composer/table/Table.css\n" +
				"src/components/composer/table/Table.tsx\n" +
				"src/components/composer/text/ComposerLink.ts\n" +
				"src/components/composer/text/Text.css\n" +
				"src/components/composer/text/Text.tsx\n" +
				"src/components/composer/toolbox/Toolbox.css\n" +
				"src/components/composer/toolbox/Toolbox.tsx\n" +
				"src/components/composer/toolbox/guide/Guide.css\n" +
				"src/components/composer/toolbox/guide/Guide.tsx\n" +
				"src/components/composer/video/Video.css\n" +
				"src/components/composer/video/Video.tsx\n" +
				"src/components/contentCreator/ContentCreator.css\n" +
				"src/components/contentCreator/ContentCreator.tsx\n" +
				"src/components/contentCreator/addNewButton/AddNewButton.css\n" +
				"src/components/contentCreator/addNewButton/AddNewButton.tsx\n" +
				"src/components/contentCreator/contentCreatorItem/ContentCreatorItem.css\n" +
				"src/components/contentCreator/contentCreatorItem/ContentCreatorItem.tsx\n" +
				"src/components/contentCreator/panels/OuterFilterPanel.tsx\n" +
				"src/components/contentCreator/panels/OuterPanel.css\n" +
				"src/components/contentCreator/pushMessageItem/PushMessageItem.css\n" +
				"src/components/contentCreator/pushMessageItem/PushMessageItem.tsx\n" +
				"src/components/contentCreatorAdmin/ContentCreatorAdmin.css\n" +
				"src/components/contentCreatorAdmin/ContentCreatorAdmin.tsx\n" +
				"src/components/contentCreatorAdmin/contentCreatorItem/ContentCreatorItem.css\n" +
				"src/components/contentCreatorAdmin/contentCreatorItem/ContentCreatorItem.tsx\n" +
				"src/components/contentCreatorAdmin/editPanel/EditPanel.tsx\n" +
				"src/components/contentCreatorAdmin/index.tsx\n" +
				"src/components/contentCreatorAdmin/stores/ContentCreatorStore.ts\n" +
				"src/components/contentCreatorAdmin/stores/index.ts\n" +
				"src/components/contentMap/ContentMap.css\n" +
				"src/components/contentMap/ContentMap.tsx\n" +
				"src/components/contentMap/index.tsx\n" +
				"src/components/contentMap/panel/DesignEditPanel.tsx\n" +
				"src/components/contentMap/store/ContentMapStore.ts\n" +
				"src/components/contentMap/store/index.ts\n" +
				"src/components/contentMapExtension/ContentMapExtension.css\n" +
				"src/components/contentMapExtension/ContentMapExtension.tsx\n" +
				"src/components/contentMapExtension/index.tsx\n" +
				"src/components/contentMapExtension/store/ContentMapExtensionStore.ts\n" +
				"src/components/contentMapExtension/store/index.ts\n" +
				"src/components/contentOrganizerAdmin/ContentOrganizerAdmin.css\n" +
				"src/components/contentOrganizerAdmin/ContentOrganizerAdmin.tsx\n" +
				"src/components/contentOrganizerAdmin/index.tsx\n" +
				"src/components/contentOrganizerAdmin/stores/ContentOrganizerAdminStore.ts\n" +
				"src/components/contentOrganizerAdmin/stores/index.ts\n" +
				"src/components/contentOrganizerAdmin/tabs/Details.css\n" +
				"src/components/contentOrganizerAdmin/tabs/Details.tsx\n" +
				"src/components/contentOrganizerGovernance/ContentOrganizerGovernance.css\n" +
				"src/components/contentOrganizerGovernance/ContentOrganizerGovernance.tsx\n" +
				"src/components/contentOrganizerGovernance/filtering/FilterPanel.tsx\n" +
				"src/components/contentOrganizerGovernance/index.tsx\n" +
				"src/components/contentOrganizerGovernance/paging/Paging.tsx\n" +
				"src/components/contentOrganizerGovernance/store/ContentOrganizerGovernanceStore.tsx\n" +
				"src/components/contentOrganizerGovernance/store/index.ts\n" +
				"src/components/contentOrganizerPortal/ContentOrganizerPortal.css\n" +
				"src/components/contentOrganizerPortal/ContentOrganizerPortal.tsx\n" +
				"src/components/contentOrganizerPortal/index.tsx\n" +
				"src/components/contentOrganizerPortal/stores/ContentOrganizerPortalStore.ts\n" +
				"src/components/contentOrganizerPortal/stores/index.ts\n" +
				"src/components/contentOrganizerWizard/Constants.ts\n" +
				"src/components/contentOrganizerWizard/ContentOrganizerWizard.css\n" +
				"src/components/contentOrganizerWizard/ContentOrganizerWizard.tsx\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerConfigPanel.css\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerConfigPanel.tsx\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerCreatePanel.css\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerCreatePanel.tsx\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerOptionsPanel.css\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerOptionsPanel.tsx\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerPermissionsTargetingPanel.css\n" +
				"src/components/contentOrganizerWizard/panels/ContentOrganizerPermissionsTargetingPanel.tsx\n" +
				"src/components/contentOrganizerWizard/panels/TimeZones.json\n" +
				"src/components/contentOrganizerWizard/permissions/ContentOrganizerPermissions.css\n" +
				"src/components/contentOrganizerWizard/permissions/ContentOrganizerPermissions.tsx\n" +
				"src/components/contentOrganizerWizard/permissions/peopleSearch/PeopleSearch.css\n" +
				"src/components/contentOrganizerWizard/permissions/peopleSearch/PeopleSearch.tsx\n" +
				"src/components/contentOrganizerWizard/progressBar/ProgressBar.css\n" +
				"src/components/contentOrganizerWizard/progressBar/ProgressBar.tsx\n" +
				"src/components/contentOrganizerWizard/progressBar/progressBar.json\n" +
				"src/components/contentOrganizerWizard/progressBar/progressBarEditMode.json\n" +
				"src/components/contentOrganizerWizard/progressBar/progressItem/ProgressItem.tsx\n" +
				"src/components/contentOrganizerWizard/stores/ContentOrganizerStore.tsx\n" +
				"src/components/contentOrganizerWizard/stores/index.ts\n" +
				"src/components/contentOrganizerWizard/wizard/Wizard.css\n" +
				"src/components/contentOrganizerWizard/wizard/Wizard.tsx\n" +
				"src/components/dateAndTimePicker/DateAndTimePicker.css\n" +
				"src/components/dateAndTimePicker/DateAndTimePicker.tsx\n" +
				"src/components/dateAndTimePicker/datePickerStyles/react-datepicker.css\n" +
				"src/components/dropDown/DropDown.css\n" +
				"src/components/dropDown/DropDown.tsx\n" +
				"src/components/dropDownIcon/DropDownIcon.css\n" +
				"src/components/dropDownIcon/DropDownIcon.tsx\n" +
				"src/components/event/index.tsx\n" +
				"src/components/fileUploader/FileUploader.css\n" +
				"src/components/fileUploader/FileUploader.tsx\n" +
				"src/components/filter/Filter.css\n" +
				"src/components/filter/Filter.tsx\n" +
				"src/components/fontStyle/FontStyle.css\n" +
				"src/components/fontStyle/FontStyle.tsx\n" +
				"src/components/global/index.tsx\n" +
				"src/components/group/Group.css\n" +
				"src/components/group/Group.tsx\n" +
				"src/components/groupList/GroupList.css\n" +
				"src/components/groupList/GroupList.tsx\n" +
				"src/components/httpError/HttpError.css\n" +
				"src/components/httpError/HttpError.tsx\n" +
				"src/components/icon/Icon.css\n" +
				"src/components/icon/Icon.tsx\n" +
				"src/components/icon/IconLibrary.json\n" +
				"src/components/icon/index.ts\n" +
				"src/components/iconDropDown/IconDropDown.css\n" +
				"src/components/iconDropDown/IconDropDown.tsx\n" +
				"src/components/iconSelector/IconSelector.css\n" +
				"src/components/iconSelector/IconSelector.tsx\n" +
				"src/components/imageCropper/CroppedImage.css\n" +
				"src/components/imageCropper/CroppedImage.tsx\n" +
				"src/components/imageCropper/ImageCropper.css\n" +
				"src/components/imageCropper/ImageCropper.tsx\n" +
				"src/components/imagePicker/ImagePicker.css\n" +
				"src/components/imagePicker/ImagePicker.tsx\n" +
				"src/components/likes/Likes.css\n" +
				"src/components/likes/Likes.tsx\n" +
				"src/components/likesAndComments/LikesAndComments.css\n" +
				"src/components/likesAndComments/LikesAndComments.tsx\n" +
				"src/components/likesAndComments/Utils.tsx\n" +
				"src/components/likesAndComments/comment/Comment.css\n" +
				"src/components/likesAndComments/comment/Comment.tsx\n" +
				"src/components/likesAndComments/newComment/IA-tinyStyles/IA-tinyStyles.css\n" +
				"src/components/likesAndComments/newComment/NewComment.css\n" +
				"src/components/likesAndComments/newComment/NewComment.tsx\n" +
				"src/components/listView/ListView.css\n" +
				"src/components/listView/ListView.tsx\n" +
				"src/components/messageBar/MessageBar.css\n" +
				"src/components/messageBar/MessageBar.tsx\n" +
				"src/components/messages/Filter.service.ts\n" +
				"src/components/messages/Index.tsx\n" +
				"src/components/messages/Messages.css\n" +
				"src/components/messages/Messages.tsx\n" +
				"src/components/messages/approvalDetails/ApprovalDetails.css\n" +
				"src/components/messages/approvalDetails/ApprovalDetails.tsx\n" +
				"src/components/messages/cardView/CardView.tsx\n" +
				"src/components/messages/carouselView/CarouselView.tsx\n" +
				"src/components/messages/compactListView/CompactListView.css\n" +
				"src/components/messages/compactListView/CompactListView.tsx\n" +
				"src/components/messages/fullView/FullView.css\n" +
				"src/components/messages/fullView/FullView.tsx\n" +
				"src/components/messages/header/Header.tsx\n" +
				"src/components/messages/listView/EventListView.tsx\n" +
				"src/components/messages/listView/ListView.css\n" +
				"src/components/messages/listView/ListView.tsx\n" +
				"src/components/messages/listView/eventList/EventList.css\n" +
				"src/components/messages/listView/eventList/EventList.tsx\n" +
				"src/components/messages/paging/Paging.tsx\n" +
				"src/components/messages/panels/EditPanel.tsx\n" +
				"src/components/messages/panels/FilterPanel.tsx\n" +
				"src/components/messages/panels/OldEditPanel.test.tsx\n" +
				"src/components/messages/panels/OldEditPanel.tsx\n" +
				"src/components/messages/panels/OldViewPanel.tsx\n" +
				"src/components/messages/panels/Panel.css\n" +
				"src/components/messages/panels/ViewPanel.tsx\n" +
				"src/components/messages/panels/tinymce.css\n" +
				"src/components/messages/rotator/Rotator.tsx\n" +
				"src/components/messages/stores/MessagesStore.ts\n" +
				"src/components/messages/stores/index.ts\n" +
				"src/components/messages/tilesView/TilesView.tsx\n" +
				"src/components/multiSelectDropDown/MultiSelectDropDown.css\n" +
				"src/components/multiSelectDropDown/MultiSelectDropDown.tsx\n" +
				"src/components/myLinks/MyLinks.css\n" +
				"src/components/myLinks/MyLinks.tsx\n" +
				"src/components/myLinks/editPanel/EditPanel.tsx\n" +
				"src/components/myLinks/index.tsx\n" +
				"src/components/myLinks/myLink/MyLink.css\n" +
				"src/components/myLinks/myLink/MyLink.tsx\n" +
				"src/components/myLinks/stores/MyLinksStore.ts\n" +
				"src/components/myLinks/stores/index.ts\n" +
				"src/components/navigator/Constants.ts\n" +
				"src/components/navigator/KeyNavigationGlobalCache.tsx\n" +
				"src/components/navigator/Navigator.css\n" +
				"src/components/navigator/Navigator.tsx\n" +
				"src/components/navigator/admin/AdminStyles.css\n" +
				"src/components/navigator/admin/Utils.ts\n" +
				"src/components/navigator/admin/admin/Admin.css\n" +
				"src/components/navigator/admin/admin/Admin.tsx\n" +
				"src/components/navigator/admin/designSettingsPanel/DesignSettingsPanel.css\n" +
				"src/components/navigator/admin/designSettingsPanel/DesignSettingsPanel.tsx\n" +
				"src/components/navigator/admin/designSettingsPanel/pivots/ElementGroupsSettings.tsx\n" +
				"src/components/navigator/admin/designSettingsPanel/pivots/ElementsSettings.tsx\n" +
				"src/components/navigator/admin/designSettingsPanel/pivots/MenuBarSettings.tsx\n" +
				"src/components/navigator/admin/designSettingsPanel/pivots/TopItemsSettings.tsx\n" +
				"src/components/navigator/admin/elementGroupSettingsPanel/ElementGroupSettingsPanel.css\n" +
				"src/components/navigator/admin/elementGroupSettingsPanel/ElementGroupSettingsPanel.tsx\n" +
				"src/components/navigator/admin/elementSettingsPanel/ElementSettingsPanel.css\n" +
				"src/components/navigator/admin/elementSettingsPanel/ElementSettingsPanel.tsx\n" +
				"src/components/navigator/admin/topItemSettingsPanel/TopItemSettingsPanel.css\n" +
				"src/components/navigator/admin/topItemSettingsPanel/TopItemSettingsPanel.tsx\n" +
				"src/components/navigator/confetti/Confetti.css\n" +
				"src/components/navigator/confetti/Confetti.tsx\n" +
				"src/components/navigator/confetti/confettiElement/ConfettiElement.css\n" +
				"src/components/navigator/confetti/confettiElement/ConfettiElement.tsx\n" +
				"src/components/navigator/configuration.json\n" +
				"src/components/navigator/contentCreatorPanel/ContentCreatorPanel.css\n" +
				"src/components/navigator/contentCreatorPanel/ContentCreatorPanel.tsx\n" +
				"src/components/navigator/eventPanel/EventPanel.css\n" +
				"src/components/navigator/eventPanel/EventPanel.tsx\n" +
				"src/components/navigator/index.tsx\n" +
				"src/components/navigator/megamenu/Megamenu.css\n" +
				"src/components/navigator/megamenu/Megamenu.tsx\n" +
				"src/components/navigator/megamenu/element/Element.css\n" +
				"src/components/navigator/megamenu/element/Element.tsx\n" +
				"src/components/navigator/megamenu/elementGroup/ElementGroup.css\n" +
				"src/components/navigator/megamenu/elementGroup/ElementGroup.tsx\n" +
				"src/components/navigator/megamenu/mobileElementGroup/MobileElementGroup.css\n" +
				"src/components/navigator/megamenu/mobileElementGroup/MobileElementGroup.tsx\n" +
				"src/components/navigator/megamenu/topItems/horizontalBar/HorizontalBar.tsx\n" +
				"src/components/navigator/megamenu/topItems/sidebar/Burgerbar.tsx\n" +
				"src/components/navigator/megamenu/topItems/topItem/TopItem.tsx\n" +
				"src/components/navigator/megamenu/topItems/topItem/TopItemDroppable.tsx\n" +
				"src/components/navigator/megamenu/topItems/verticalBar/VerticalBar.tsx\n" +
				"src/components/navigator/messagePanel/MessagePanel.tsx\n" +
				"src/components/navigator/peopleFinderPanel/PeopleFinderPanel.css\n" +
				"src/components/navigator/peopleFinderPanel/PeopleFinderPanel.tsx\n" +
				"src/components/navigator/phonebook/Phonebook.css\n" +
				"src/components/navigator/phonebook/Phonebook.tsx\n" +
				"src/components/navigator/phonebook/peopleCard/PeopleCard.css\n" +
				"src/components/navigator/phonebook/peopleCard/PeopleCard.test.tsx\n" +
				"src/components/navigator/phonebook/peopleCard/PeopleCard.tsx\n" +
				"src/components/navigator/smartmenu/Smartmenu.css\n" +
				"src/components/navigator/smartmenu/Smartmenu.tsx\n" +
				"src/components/navigator/smartmenu/SmartmenuTopItemDroppable.tsx\n" +
				"src/components/navigator/smartmenu/test.json\n" +
				"src/components/navigator/stores/NavigatorStore.tsx\n" +
				"src/components/navigator/stores/index.ts\n" +
				"src/components/numberField/NumberField.css\n" +
				"src/components/numberField/NumberField.tsx\n" +
				"src/components/optionSelector/OptionSelector.css\n" +
				"src/components/optionSelector/OptionSelector.tsx\n" +
				"src/components/orgAssetsAdmin/OrgAssetsAdmin.css\n" +
				"src/components/orgAssetsAdmin/OrgAssetsAdmin.tsx\n" +
				"src/components/orgAssetsAdmin/index.tsx\n" +
				"src/components/orgAssetsAdmin/panels/Panel.css\n" +
				"src/components/orgAssetsAdmin/panels/ViewPanel.tsx\n" +
				"src/components/orgAssetsAdmin/stores/OrgAssetsAdminStore.tsx\n" +
				"src/components/orgAssetsAdmin/stores/index.ts\n" +
				"src/components/orgAssetsUploader/OrgAssetsUploader.css\n" +
				"src/components/orgAssetsUploader/OrgAssetsUploader.tsx\n" +
				"src/components/orgAssetsUploader/cards/OrgAssetsImageCard.css\n" +
				"src/components/orgAssetsUploader/cards/OrgAssetsImageCard.tsx\n" +
				"src/components/orgAssetsUploader/panels/OrgAssetsPanel.css\n" +
				"src/components/orgAssetsUploader/panels/OrgAssetsPanel.tsx\n" +
				"src/components/panels/FullscreenPanel.tsx\n" +
				"src/components/panels/Panel.css\n" +
				"src/components/panels/Panel.tsx\n" +
				"src/components/panels/authors/IAAuthors.css\n" +
				"src/components/panels/authors/IAAuthors.tsx\n" +
				"src/components/panels/imageViewer/ImageViewer.css\n" +
				"src/components/panels/imageViewer/ImageViewer.tsx\n" +
				"src/components/panels/index.tsx\n" +
				"src/components/panels/navigationBar/NavigationBar.css\n" +
				"src/components/panels/navigationBar/NavigationBar.tsx\n" +
				"src/components/peopleCard/peopleCard.css\n" +
				"src/components/peopleCard/peopleCard.tsx\n" +
				"src/components/peopleFinder/PeopleFinder.css\n" +
				"src/components/peopleFinder/PeopleFinder.tsx\n" +
				"src/components/peopleFinder/card/PeopleFinderCard.css\n" +
				"src/components/peopleFinder/card/PeopleFinderCard.tsx\n" +
				"src/components/peopleFinder/header/PeopleFinderHeader.css\n" +
				"src/components/peopleFinder/header/PeopleFinderHeader.tsx\n" +
				"src/components/peopleFinder/index.tsx\n" +
				"src/components/peopleFinder/multiSelectDropDown/PeopleFinderMultiSelectDropDown.css\n" +
				"src/components/peopleFinder/multiSelectDropDown/PeopleFinderMultiSelectDropDown.tsx\n" +
				"src/components/peopleFinder/panel/PeopleFinderPanel.css\n" +
				"src/components/peopleFinder/panel/PeopleFinderPanel.tsx\n" +
				"src/components/peopleFinder/search/PeopleFinderSearch.css\n" +
				"src/components/peopleFinder/search/PeopleFinderSearch.tsx\n" +
				"src/components/peopleFinder/stores/PeopleFinderStore.ts\n" +
				"src/components/peopleSearch/PeopleSearch.css\n" +
				"src/components/peopleSearch/PeopleSearch.tsx\n" +
				"src/components/permissions/Permissions.css\n" +
				"src/components/permissions/Permissions.tsx\n" +
				"src/components/permissions/index.tsx\n" +
				"src/components/permissions/permissionsPanel/PermissionsPanel.tsx\n" +
				"src/components/permissions/permissionsPanel/peopleSearch/PeopleSearch.css\n" +
				"src/components/permissions/permissionsPanel/peopleSearch/PeopleSearch.tsx\n" +
				"src/components/permissions/permissionsPanel/permissionSwitch/PermissionSwitch.tsx\n" +
				"src/components/permissions/stores/PermissionsStore.ts\n" +
				"src/components/permissions/stores/index.ts\n" +
				"src/components/personaImage/PersonaImage.css\n" +
				"src/components/personaImage/PersonaImage.tsx\n" +
				"src/components/personaSmall/PersonaSmall.css\n" +
				"src/components/personaSmall/PersonaSmall.tsx\n" +
				"src/components/phonebook/Phonebook.css\n" +
				"src/components/phonebook/Phonebook.tsx\n" +
				"src/components/phonebook/peopleCard/PeopleCard.css\n" +
				"src/components/phonebook/peopleCard/PeopleCard.tsx\n" +
				"src/components/pivot/Pivot.css\n" +
				"src/components/pivot/Pivot.tsx\n" +
				"src/components/playAdmin/Index.tsx\n" +
				"src/components/playAdmin/PlayAdmin.css\n" +
				"src/components/playAdmin/PlayAdmin.tsx\n" +
				"src/components/playAdmin/PlayHelper.ts\n" +
				"src/components/playAdmin/dashboard/Dashboard.css\n" +
				"src/components/playAdmin/dashboard/Dashboard.tsx\n" +
				"src/components/playAdmin/dashboard/articles/Articles.css\n" +
				"src/components/playAdmin/dashboard/articles/Articles.tsx\n" +
				"src/components/playAdmin/dashboard/articles/articleEditPanel/ArticleEditPanel.css\n" +
				"src/components/playAdmin/dashboard/articles/articleEditPanel/ArticleEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/cardView/CardView.css\n" +
				"src/components/playAdmin/dashboard/cardView/CardView.tsx\n" +
				"src/components/playAdmin/dashboard/cardView/card/Card.css\n" +
				"src/components/playAdmin/dashboard/cardView/card/Card.tsx\n" +
				"src/components/playAdmin/dashboard/group/Group.css\n" +
				"src/components/playAdmin/dashboard/group/Group.tsx\n" +
				"src/components/playAdmin/dashboard/header/Header.css\n" +
				"src/components/playAdmin/dashboard/header/Header.tsx\n" +
				"src/components/playAdmin/dashboard/listView/ListView.css\n" +
				"src/components/playAdmin/dashboard/listView/ListView.tsx\n" +
				"src/components/playAdmin/dashboard/listView/listElement/ListElement.css\n" +
				"src/components/playAdmin/dashboard/listView/listElement/ListElement.tsx\n" +
				"src/components/playAdmin/dashboard/listView/listElementHeader/ListElementHeader.css\n" +
				"src/components/playAdmin/dashboard/listView/listElementHeader/ListElementHeader.tsx\n" +
				"src/components/playAdmin/dashboard/mediaFiles/MediaFiles.css\n" +
				"src/components/playAdmin/dashboard/mediaFiles/MediaFiles.tsx\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/MediaFileSelector.css\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/MediaFileSelector.tsx\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/mediaFileSelectorPanel/MediaFileSelectorPanel.css\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/mediaFileSelectorPanel/MediaFileSelectorPanel.tsx\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/mediaFileUploadPanel/MediaFileUploadPanel.css\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/mediaFileUploadPanel/MediaFileUploadPanel.tsx\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/stockPhotosPanel/StockPhotosPanel.css\n" +
				"src/components/playAdmin/dashboard/mediaFiles/mediaFileSelector/stockPhotosPanel/StockPhotosPanel.tsx\n" +
				"src/components/playAdmin/dashboard/players/Players.css\n" +
				"src/components/playAdmin/dashboard/players/Players.tsx\n" +
				"src/components/playAdmin/dashboard/players/connectingNewPlayerPopup/ConnectingNewPlayerPopup.css\n" +
				"src/components/playAdmin/dashboard/players/connectingNewPlayerPopup/ConnectingNewPlayerPopup.tsx\n" +
				"src/components/playAdmin/dashboard/players/playerEditPanel/PlayerEditPanel.css\n" +
				"src/components/playAdmin/dashboard/players/playerEditPanel/PlayerEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/playlists/Playlists.css\n" +
				"src/components/playAdmin/dashboard/playlists/Playlists.tsx\n" +
				"src/components/playAdmin/dashboard/playlists/PlaylistsContent.tsx\n" +
				"src/components/playAdmin/dashboard/playlists/playlistEditPanel/PlaylistEditPanel.css\n" +
				"src/components/playAdmin/dashboard/playlists/playlistEditPanel/PlaylistEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/popup/Popup.css\n" +
				"src/components/playAdmin/dashboard/popup/Popup.tsx\n" +
				"src/components/playAdmin/dashboard/settings/Settings.css\n" +
				"src/components/playAdmin/dashboard/settings/Settings.tsx\n" +
				"src/components/playAdmin/dashboard/settings/groups/Groups.css\n" +
				"src/components/playAdmin/dashboard/settings/groups/Groups.tsx\n" +
				"src/components/playAdmin/dashboard/settings/groups/groupEditPanel/GroupEditPanel.css\n" +
				"src/components/playAdmin/dashboard/settings/groups/groupEditPanel/GroupEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/settings/permissions/Permissions.css\n" +
				"src/components/playAdmin/dashboard/settings/permissions/Permissions.tsx\n" +
				"src/components/playAdmin/dashboard/settings/permissions/permissionsEditPanel/PermissionsEditPanel.css\n" +
				"src/components/playAdmin/dashboard/settings/permissions/permissionsEditPanel/PermissionsEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/settings/permissions/permissionsEditPanel/permissionsPersona/PermissionPersona.tsx\n" +
				"src/components/playAdmin/dashboard/settings/permissions/permissionsEditPanel/permissionsPersona/PermissionsPersona.css\n" +
				"src/components/playAdmin/dashboard/settings/profile/Profile.css\n" +
				"src/components/playAdmin/dashboard/settings/profile/Profile.tsx\n" +
				"src/components/playAdmin/dashboard/slides/Slides.css\n" +
				"src/components/playAdmin/dashboard/slides/Slides.tsx\n" +
				"src/components/playAdmin/dashboard/slides/SlidesContent.tsx\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/SlideEditPanel.css\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/SlideEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/rssTickerPopup/RssTickerPopup.css\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/rssTickerPopup/RssTickerPopup.tsx\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/widgetPopup/WidgetPopup.css\n" +
				"src/components/playAdmin/dashboard/slides/slideEditPanel/widgetPopup/WidgetPopup.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/Widgets.css\n" +
				"src/components/playAdmin/dashboard/widgets/Widgets.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/WidgetEditPanel.css\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/WidgetEditPanel.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/ArticleViewerWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/EmbedWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/GalleryWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/ImageWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/PdfWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/RssTickerWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/RssWidgetSettings.tsx\n" +
				"src/components/playAdmin/dashboard/widgets/widgetEditPanel/widgetSettings/VideoWidgetSettings.tsx\n" +
				"src/components/playAdmin/menu/Menu.css\n" +
				"src/components/playAdmin/menu/Menu.tsx\n" +
				"src/components/playAdmin/menu/menuItem/MenuItem.css\n" +
				"src/components/playAdmin/menu/menuItem/MenuItem.tsx\n" +
				"src/components/playAdmin/menu/mobileMenu/MobileMenu.css\n" +
				"src/components/playAdmin/menu/mobileMenu/MobileMenu.tsx\n" +
				"src/components/playAdmin/stores/Store.ts\n" +
				"src/components/playAdmin/stores/index.ts\n" +
				"src/components/player/Index.tsx\n" +
				"src/components/player/Player.css\n" +
				"src/components/player/Player.tsx\n" +
				"src/components/player/footer/Footer.css\n" +
				"src/components/player/footer/Footer.tsx\n" +
				"src/components/player/footer/footerWeather/FooterWeather.css\n" +
				"src/components/player/footer/footerWeather/FooterWeather.tsx\n" +
				"src/components/player/rssTicker/RssTicker.css\n" +
				"src/components/player/rssTicker/RssTicker.tsx\n" +
				"src/components/player/slide/Slide.css\n" +
				"src/components/player/slide/Slide.tsx\n" +
				"src/components/player/slide/Widget.tsx\n" +
				"src/components/player/slide/articleViewer/ArticleViewer.css\n" +
				"src/components/player/slide/articleViewer/ArticleViewer.tsx\n" +
				"src/components/player/slide/articleViewer/article/Article.css\n" +
				"src/components/player/slide/articleViewer/article/Article.tsx\n" +
				"src/components/player/slide/gallery/Gallery.css\n" +
				"src/components/player/slide/gallery/Gallery.tsx\n" +
				"src/components/player/slide/rss/Rss.css\n" +
				"src/components/player/slide/rss/Rss.tsx\n" +
				"src/components/player/stores/Store.ts\n" +
				"src/components/player/stores/index.ts\n" +
				"src/components/popup/Popup.css\n" +
				"src/components/popup/Popup.tsx\n" +
				"src/components/progressView/IAProgressView.css\n" +
				"src/components/progressView/IAProgressView.tsx\n" +
				"src/components/progressView/progressBar/ProgressBar.css\n" +
				"src/components/progressView/progressBar/ProgressBar.tsx\n" +
				"src/components/progressView/progressList/ProgressList.css\n" +
				"src/components/progressView/progressList/ProgressList.tsx\n" +
				"src/components/progressView/progressList/progressList.json\n" +
				"src/components/progressView/progressList/progressListItem/ProgressListItem.css\n" +
				"src/components/progressView/progressList/progressListItem/ProgressListItem.tsx\n" +
				"src/components/rotator/Rotator.css\n" +
				"src/components/rotator/Rotator.service.ts\n" +
				"src/components/rotator/Rotator.test.tsx\n" +
				"src/components/rotator/Rotator.tsx\n" +
				"src/components/search/Search.css\n" +
				"src/components/search/Search.tsx\n" +
				"src/components/siteListRadioDropDown/SiteListRadioDropDown.css\n" +
				"src/components/siteListRadioDropDown/SiteListRadioDropDown.tsx\n" +
				"src/components/slider/Slider.css\n" +
				"src/components/slider/Slider.tsx\n" +
				"src/components/smallMenu/smallMenu.css\n" +
				"src/components/smallMenu/smallMenu.tsx\n" +
				"src/components/spinner/Spinner.css\n" +
				"src/components/spinner/Spinner.test.tsx\n" +
				"src/components/spinner/Spinner.tsx\n" +
				"src/components/stockPhotosPanel/StockPhotosPanel.css\n" +
				"src/components/stockPhotosPanel/StockPhotosPanel.tsx\n" +
				"src/components/targetingAdmin/Index.tsx\n" +
				"src/components/targetingAdmin/TargetingAdmin.tsx\n" +
				"src/components/targetingAdmin/components/applications/Applications.tsx\n" +
				"src/components/targetingAdmin/components/applications/ApplicationsSettings.css\n" +
				"src/components/targetingAdmin/components/applications/ApplicationsSettings.tsx\n" +
				"src/components/targetingAdmin/components/profileData/ProfileData.tsx\n" +
				"src/components/targetingAdmin/components/profileData/PropertyPanel.css\n" +
				"src/components/targetingAdmin/components/profileData/PropertyPanel.tsx\n" +
				"src/components/targetingAdmin/components/profileData/SyncPanel.css\n" +
				"src/components/targetingAdmin/components/profileData/SyncPanel.tsx\n" +
				"src/components/targetingAdmin/components/userGroup/EditPanel.tsx\n" +
				"src/components/targetingAdmin/components/userGroup/Panel.css\n" +
				"src/components/targetingAdmin/components/userGroup/UserGroup.css\n" +
				"src/components/targetingAdmin/components/userGroup/UserGroup.tsx\n" +
				"src/components/targetingAdmin/stores/TargetingAdminStore.tsx\n" +
				"src/components/targetingAdmin/stores/index.ts\n" +
				"src/components/targetingApplication/TargetingApplication.css\n" +
				"src/components/targetingApplication/TargetingApplication.tsx\n" +
				"src/components/teams/Teams.css\n" +
				"src/components/teams/Teams.tsx\n" +
				"src/components/teams/index.tsx\n" +
				"src/components/teams/stores/TeamsStore.ts\n" +
				"src/components/teams/stores/index.ts\n" +
				"src/components/teams/teamsCard/TeamsCard.css\n" +
				"src/components/teams/teamsCard/TeamsCard.tsx\n" +
				"src/components/termCheckBox/TermCheckbox.css\n" +
				"src/components/termCheckBox/TermCheckbox.tsx\n" +
				"src/components/termCheckBox/index.ts\n" +
				"src/components/termCheckIE/TermCheckbox.css\n" +
				"src/components/termCheckIE/TermCheckboxIE.tsx\n" +
				"src/components/termCheckIE/index.ts\n" +
				"src/components/textField/TextField.css\n" +
				"src/components/textField/TextField.tsx\n" +
				"src/components/theme/Theme.css\n" +
				"src/components/theme/Theme.tsx\n" +
				"src/components/theme/cardView/CardView.tsx\n" +
				"src/components/theme/cardView/card/Card.css\n" +
				"src/components/theme/cardView/card/Card.tsx\n" +
				"src/components/theme/index.tsx\n" +
				"src/components/theme/panels/Panel.css\n" +
				"src/components/theme/panels/ViewPanel.tsx\n" +
				"src/components/theme/stores/ThemeStore.tsx\n" +
				"src/components/theme/stores/index.ts\n" +
				"src/components/tilesView/TilesView.css\n" +
				"src/components/tilesView/TilesView.tsx\n" +
				"src/components/tilesView/tilesContentElement/tilesContentElement.tsx\n" +
				"src/components/toggle/Toggle.css\n" +
				"src/components/toggle/Toggle.tsx\n" +
				"src/components/tooltip/Tooltip.css\n" +
				"src/components/tooltip/Tooltip.tsx\n" +
				"src/components/treeLink/TreeLink.css\n" +
				"src/components/treeLink/TreeLink.tsx\n" +
				"src/components/treeLink/index.tsx\n" +
				"src/components/treeLink/panel/EditPanel.tsx\n" +
				"src/components/treeLink/store/TreeLinkStore.ts\n" +
				"src/components/treeLink/store/index.ts\n" +
				"src/components/treeLink/treeLinkNode/TreeLinkNode.css\n" +
				"src/components/treeLink/treeLinkNode/TreeLinkNode.tsx\n" +
				"src/components/treeTargeting/TreeTargeting.css\n" +
				"src/components/treeTargeting/TreeTargeting.test.tsx\n" +
				"src/components/treeTargeting/TreeTargeting.tsx\n" +
				"src/components/treeTargeting/index.ts\n" +
				"src/components/treeTargeting/treeNode/TreeNode.tsx\n" +
				"src/components/treeTargeting/utils.ts\n" +
				"src/components/treeview/TreeView.test.ts\n" +
				"src/components/treeview/TreeViewStore.tsx\n" +
				"src/components/treeview/Treeview.css\n" +
				"src/components/treeview/Treeview.tsx\n" +
				"src/components/treeview/treeViewItem/TreeViewItem.tsx\n" +
				"src/components/uniqueViews/UniqueViews.css\n" +
				"src/components/uniqueViews/UniqueViews.tsx\n" +
				"src/components/viewer/Viewer.css\n" +
				"src/components/viewer/Viewer.tsx\n" +
				"src/components/webpartIntro/WebpartIntro.css\n" +
				"src/components/webpartIntro/WebpartIntro.tsx\n" +
				"src/global/Constants.ts\n" +
				"src/global/Container.ts\n" +
				"src/global/ResizeObserver.d.ts\n" +
				"src/global/index.ts\n" +
				"src/images/active.svg\n" +
				"src/images/burger.png\n" +
				"src/images/clear.png\n" +
				"src/images/close.png\n" +
				"src/images/horizontal.png\n" +
				"src/images/ia-app.svg\n" +
				"src/images/ia-spapp.svg\n" +
				"src/images/intraactive-logo.png\n" +
				"src/images/logout.png\n" +
				"src/images/no-image-selected.png\n" +
				"src/images/preview.png\n" +
				"src/images/profile.png\n" +
				"src/images/spinner.png\n" +
				"src/images/spinning-loading.gif\n" +
				"src/images/stream-large.png\n" +
				"src/images/stream-thumbnail.png\n" +
				"src/images/upload.png\n" +
				"src/images/video-play-button.png\n" +
				"src/images/wizard1.svg\n" +
				"src/images/wizard2.svg\n" +
				"src/images/wizard3.svg\n" +
				"src/images/wizard4.svg\n" +
				"src/images/wizard5.svg\n" +
				"src/images/wizard6.svg\n" +
				"src/index.ts\n" +
				"src/interfaces/Components.ts\n" +
				"src/interfaces/IAItem.ts\n" +
				"src/interfaces/IARotator.ts\n" +
				"src/interfaces/IAccordion.ts\n" +
				"src/interfaces/IAppComponent.ts\n" +
				"src/interfaces/IAppDesign.ts\n" +
				"src/interfaces/IAppPage.ts\n" +
				"src/interfaces/IAppPush.ts\n" +
				"src/interfaces/IApplication.ts\n" +
				"src/interfaces/IApprover.ts\n" +
				"src/interfaces/IBirthdayUser.ts\n" +
				"src/interfaces/IBotStatus.ts\n" +
				"src/interfaces/ICard.ts\n" +
				"src/interfaces/ICardCover.ts\n" +
				"src/interfaces/ICardDesign.ts\n" +
				"src/interfaces/ICarouselContentElement.ts\n" +
				"src/interfaces/ICategory.ts\n" +
				"src/interfaces/ICategoryAdmin.ts\n" +
				"src/interfaces/ICheckOut.ts\n" +
				"src/interfaces/ICombinedUserResult.ts\n" +
				"src/interfaces/IComment.ts\n" +
				"src/interfaces/IComponentInstances.ts\n" +
				"src/interfaces/IComposerGallery.ts\n" +
				"src/interfaces/IComposerImage.ts\n" +
				"src/interfaces/IComposerTool.ts\n" +
				"src/interfaces/IComposerVideo.ts\n" +
				"src/interfaces/IConfig.ts\n" +
				"src/interfaces/IContentCreator.ts\n" +
				"src/interfaces/IContentCreatorItem.ts\n" +
				"src/interfaces/IContentMap.ts\n" +
				"src/interfaces/IContentOrganizerCheckPermissionsResult.ts\n" +
				"src/interfaces/IContentOrganizerCreate.ts\n" +
				"src/interfaces/IContentOrganizerCustomStatus.ts\n" +
				"src/interfaces/IContentOrganizerSearchResult.ts\n" +
				"src/interfaces/IContentResponsible.ts\n" +
				"src/interfaces/ICreatePageFromTemplate.ts\n" +
				"src/interfaces/ICreatePageFromTemplateResponse.ts\n" +
				"src/interfaces/ICropSetting.ts\n" +
				"src/interfaces/IDesign.ts\n" +
				"src/interfaces/IDocumentLibrary.ts\n" +
				"src/interfaces/IDraft.ts\n" +
				"src/interfaces/IDurableFunctionRuntimeStatus.ts\n" +
				"src/interfaces/IDurableFunctionStatus.ts\n" +
				"src/interfaces/IElement.ts\n" +
				"src/interfaces/IElementGroup.ts\n" +
				"src/interfaces/IEventSettings.ts\n" +
				"src/interfaces/IFilter.ts\n" +
				"src/interfaces/IFilterDataContentOrganizer.ts\n" +
				"src/interfaces/IFilterDataMessages.ts\n" +
				"src/interfaces/IGroupList.ts\n" +
				"src/interfaces/IHeader.ts\n" +
				"src/interfaces/IHttpStatus.ts\n" +
				"src/interfaces/IHubSite.ts\n" +
				"src/interfaces/IIconDropDown.ts\n" +
				"src/interfaces/IInstance.ts\n" +
				"src/interfaces/IInstanceSettings.ts\n" +
				"src/interfaces/IItem.ts\n" +
				"src/interfaces/IItemData.ts\n" +
				"src/interfaces/ILabel.ts\n" +
				"src/interfaces/ILanguage.ts\n" +
				"src/interfaces/ILike.ts\n" +
				"src/interfaces/IMegamenu.ts\n" +
				"src/interfaces/IMessage.ts\n" +
				"src/interfaces/IMessageAnalytics.ts\n" +
				"src/interfaces/IMessageFilter.ts\n" +
				"src/interfaces/IMessageResult.ts\n" +
				"src/interfaces/IMessageTrackingData.ts\n" +
				"src/interfaces/IMessageTrackingDataOverview.ts\n" +
				"src/interfaces/IMessageTrackingDataUser.ts\n" +
				"src/interfaces/IMessagesSettings.ts\n" +
				"src/interfaces/IMobileDevicesAnalytics.ts\n" +
				"src/interfaces/IMyContent.ts\n" +
				"src/interfaces/IMyContentItem.ts\n" +
				"src/interfaces/IMyLink.ts\n" +
				"src/interfaces/INavigator.ts\n" +
				"src/interfaces/INavigatorResponse.ts\n" +
				"src/interfaces/INode.ts\n" +
				"src/interfaces/INodeGroup.ts\n" +
				"src/interfaces/INodeTerm.ts\n" +
				"src/interfaces/IOption.ts\n" +
				"src/interfaces/IOrgAssetFile.ts\n" +
				"src/interfaces/IOrgAssetLibraryUrl.ts\n" +
				"src/interfaces/IOrgAssetsInfo.ts\n" +
				"src/interfaces/IOrgAssetsSettings.ts\n" +
				"src/interfaces/IOrgAssetsThumbnail.ts\n" +
				"src/interfaces/IPeopleFinderDesign.ts\n" +
				"src/interfaces/IPeopleFinderFilter.ts\n" +
				"src/interfaces/IPeopleFinderPerson.ts\n" +
				"src/interfaces/IPeopleInfo.ts\n" +
				"src/interfaces/IPeopleProperty.ts\n" +
				"src/interfaces/IPermissionResponse.ts\n" +
				"src/interfaces/IPlay.ts\n" +
				"src/interfaces/IPlayHeader.ts\n" +
				"src/interfaces/IPlayMenuItem.ts\n" +
				"src/interfaces/IProgressViewStatus.ts\n" +
				"src/interfaces/IReply.ts\n" +
				"src/interfaces/IRevisionDate.ts\n" +
				"src/interfaces/IRss.ts\n" +
				"src/interfaces/ISPEvent.ts\n" +
				"src/interfaces/ISPMessage.ts\n" +
				"src/interfaces/ISharePointUser.ts\n" +
				"src/interfaces/ISite.ts\n" +
				"src/interfaces/ISmartmenu.ts\n" +
				"src/interfaces/IStockImagesSearchResult.ts\n" +
				"src/interfaces/ITargetTerm.ts\n" +
				"src/interfaces/ITargeting.ts\n" +
				"src/interfaces/ITargetingApplications.ts\n" +
				"src/interfaces/ITargetingDataModel.ts\n" +
				"src/interfaces/ITargetingExistingStructure.ts\n" +
				"src/interfaces/ITargetingFields.ts\n" +
				"src/interfaces/ITargetingGroup.ts\n" +
				"src/interfaces/ITargetingGroupValues.ts\n" +
				"src/interfaces/ITargetingItemData.ts\n" +
				"src/interfaces/ITargetingProperties.ts\n" +
				"src/interfaces/ITargetingTerm.ts\n" +
				"src/interfaces/ITenantSettings.ts\n" +
				"src/interfaces/ITerm.ts\n" +
				"src/interfaces/ITermResult.ts\n" +
				"src/interfaces/ITheme.ts\n" +
				"src/interfaces/IThemePalette.ts\n" +
				"src/interfaces/ITilesContentElement.ts\n" +
				"src/interfaces/ITopItem.ts\n" +
				"src/interfaces/ITreeLinkNode.ts\n" +
				"src/interfaces/ITreeLinkNodeConfig.ts\n" +
				"src/interfaces/ITreeViewItem.ts\n" +
				"src/interfaces/IUpdateContentOrganizerFeaturedImage.ts\n" +
				"src/interfaces/IUser.ts\n" +
				"src/interfaces/IUserPermission.ts\n" +
				"src/interfaces/IUserResult.ts\n" +
				"src/interfaces/IUserRole.ts\n" +
				"src/interfaces/IVersion.ts\n" +
				"src/interfaces/OrgAssets/CdnTypeEnum.ts\n" +
				"src/interfaces/OrgAssets/ErrorResponse.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetAddRequest.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetRemoveRequest.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetUpdateRequest.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetsData.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetsItem.ts\n" +
				"src/interfaces/OrgAssets/IOrgAssetsLibraries.ts\n" +
				"src/interfaces/OrgAssets/IResourcePath.ts\n" +
				"src/interfaces/OrgAssets/OrgAssetStatusEnum.ts\n" +
				"src/interfaces/OrgAssets/OrgAssetTypeEnum.ts\n" +
				"src/interfaces/UniquePermissionsResult.ts\n" +
				"src/localization/Danish.json\n" +
				"src/localization/English.json\n" +
				"src/localization/German.json\n" +
				"src/localization/Norwegian.json\n" +
				"src/localization/Portuguese.json\n" +
				"src/localization/Swedish.json\n" +
				"src/services/AdvancedSettingsService.ts\n" +
				"src/services/AnalyticsService.ts\n" +
				"src/services/BirthdayService.ts\n" +
				"src/services/BotService.ts\n" +
				"src/services/CategoryService.ts\n" +
				"src/services/ConditionalOutput.test.ts\n" +
				"src/services/ConditionalOutput.ts\n" +
				"src/services/ConditionalOutputFactory.test.ts\n" +
				"src/services/ConditionalOutputFactory.ts\n" +
				"src/services/ConditionalOutputType.ts\n" +
				"src/services/ContentCreatorService.ts\n" +
				"src/services/ContentOrganizerService.ts\n" +
				"src/services/DateTimeService.test.ts\n" +
				"src/services/DateTimeService.ts\n" +
				"src/services/Environment.ts\n" +
				"src/services/EventService.ts\n" +
				"src/services/ImageService.ts\n" +
				"src/services/InstanceService.ts\n" +
				"src/services/LocalizationService.test.ts\n" +
				"src/services/LocalizationService.ts\n" +
				"src/services/LoggingService.ts\n" +
				"src/services/MessageService.tsx\n" +
				"src/services/NativeService.ts\n" +
				"src/services/NavigatorService.tsx\n" +
				"src/services/OrgAssetsService.ts\n" +
				"src/services/PeopleFinderService.ts\n" +
				"src/services/PermissionsService.ts\n" +
				"src/services/PhonebookService.tsx\n" +
				"src/services/PlayService.ts\n" +
				"src/services/PushService.tsx\n" +
				"src/services/RssService.ts\n" +
				"src/services/SocialService.ts\n" +
				"src/services/StreamService.ts\n" +
				"src/services/TargetingService.ts\n" +
				"src/services/TeamsService.ts\n" +
				"src/services/ThemeService.ts\n" +
				"src/services/TranslationService.ts\n" +
				"src/services/UploaderService.tsx\n" +
				"src/services/UserService.ts\n" +
				"src/styles/BasicIA.css\n" +
				"src/styles/Sharepoint_4.css";

		// neo4jDriver.addWebpartRelation(sdkuiPart, webParts);
		 //neo4jDriver.createSdkUi(sdkui);

		//System.out.println(neo4jDriver.GetWPRecommendation("src/components/analytics/tabs/MessagesTab.tsx\nsrc/components/analytics/tabs/MobileDevicesTab.tsx"));
	}



}

